package kostat.lbdms.ServiceAPI.common.web.rest.constant;

/**  
* <pre>
* Command 호출 Key 관리 클래스
* </pre>
*
* @author        Admin
* @since         2015. 10. 20. 오후 2:18:53
* @version         1.0
* @see
* <pre>
*  ==========  개정이력( Modification Information )  ==========  
* 
*     수정일             수정자                         수정내용
*  ------------    ------------     -------------------------------
*   2015.09.11.      Admin                        최초생성
* 
* </pre>
*/
public interface Command {
    String ACTION = "ACTION";
	
	String COLLECT = "COLLECT";
	
	String INSERT = "INSERT";
	 
	String UPDATE = "UPDATE";
	
	String DETAIL = "DETAIL";
	
	String DELETE = "DELETE";
	
	String DELETE_ACTIONS = "DELETE_ACTIONS";
	
	String SELECT = "SELECT";
	
	String SELECT_CATEGORIZE = "SELECT_CATEGORIZE";
	
	String START = "START";
	
	String QUERY_MULTI_START = "QUERY_MULTI_START";
	
	String URL_TEST = "URL_TEST";
	
	String API = "API";

	String EXECUTE = "EXECUTE";

	String DB = "DB";
	
	String FILE = "FILE";

	String RESOURCE = "RESOURCE";

	String HDFS = "HDFS";

	String FILELIST = "FILELIST";

	String SEND = "SEND";
	
	String CRUD = "CRUD";

	String COPY = "COPY";

	String LIST = "LIST";

	String PREVIEW = "PREVIEW";
	
	String DATAFLOW_PREVIEW = "DATAFLOW_PREVIEW";

	String LOG = "LOG";

	String MKDIR = "MKDIR";

	String MOVE = "MOVE";

	String FILE_CONTENT_ENCODING = "FILE_CONTENT_ENCODING";

	String FILE_ENCODING = "FILE_ENCODING";

	String EXCEL_CHANGE = "EXCEL_CHANGE";

	String RENAME = "RENAME";

	String HIVE = "HIVE";

	String DATABASE_LIST = "DATABASE_LIST";

	String TABLE_LIST = "TABLE_LIST";

	String TABLE_INFO = "TABLE_INFO";

	String QUERY = "QUERY";

	String TABLE_PREVIEW = "TABLE_PREVIEW";

	String CLOSE = "CLOSE";

	String TABLE_DELETE = "TABLE_DELETE";

	String DATABASE_DELETE = "DATABASE_DELETE";

	String TABLE_CREATE = "TABLE_CREATE";
	
	String DATABASE_CREATE = "DATABASE_CREATE";

	String MODIFY = "MODIFY";

	String PROFILE_TABLE = "PROFILE_TABLE";

	String PROFILING = "PROFILING";

	String PROFILE_FILE = "PROFILE_FILE";

	String SHP_UPLOAD = "SHP_UPLOAD";

	String POSTGRE = "POSTGRE";

	String CREATE_TABLE = "CREATE_TABLE";

	String INSERT_TABLE = "INSERT_TABLE";

	String TABLES = "TABLES";

	String DATABASES = "DATABASES";

	String ALTER_TABLE = "ALTER_TABLE";

	String EXECUTE_QUERY = "EXECUTE_QUERY";

	String DROP_TABLE = "DROP_TABLE";

	String DROP_DB = "DROP_DB";

	String AGENT = "AGENT";

	String AGENT_INFO = "AGENT_INFO";

	String SCHEDULE = "SCHEDULE";

	String USE_CHANGE = "USE_CHANGE";

	String MANAGE = "MANAGE";

	String HADOOP = "HADOOP";

	String REVOKE = "REVOKE";
	
	String PG_SCHEMA_CHECK = "PG_SCHEMA_CHECK";
	
	String GRANT = "GRANT";
	
	String GET_CPU_MEMORY = "GET_CPU_MEMORY";

	String PG_GET_CPU_MEMORY = "PG_GET_CPU_MEMORY";

	String GET_DISK = "GET_DISK";

	String SUM_CPU_MEMORY = "SUM_CPU_MEMORY";

	String COORDINATE_TRANSFORM = "COORDINATE_TRANSFORM";

	String STOP = "STOP";
	
	String ONE_LINE = "ONE_LINE";

	String EXECUTE_TABLE = "EXECUTE_TABLE";
	
	String EXECUTE_FILE = "EXECUTE_FILE";

	String COORDINATE_LIST = "COORDINATE_LIST";

	String SEARCH_ENCODE = "SEARCH_ENCODE";
	
	String SEARCH_ENCODE2 = "SEARCH_ENCODE2";

	String WORKFLOW = "WORKFLOW";

	String EXECUTE_CRUD = "EXECUTE_CRUD";

	String CHECK_ACTION = "CHECK_ACTION";

	String CANCEL = "CANCEL";

	String QUERY_RESULT = "QUERY_RESULT";

	String QUERY_RESULT_COUNT = "QUERY_RESULT_COUNT";

	String MAPPING = "MAPPING";
	
	String VERIFY = "VERIFY";

	String MODFIY = "MODIFY";

	String DATA_LOAD = "DATA_LOAD";

	String MODIFY_DETAIL_EXECUTE = "MODIFY_DETAIL_EXECUTE";

	String MODIFY_RESULT = "MODIFY_RESULT";
	
	String ANALYSIS = "ANALYSIS";
	
	String GEO_ANALYSIS = "GEO_ANALYSIS";
	
	String BUFFER_ANALYSIS = "BUFFER_ANALYSIS";
	
	String R_ANALYSIS = "R_ANALYSIS";
	
	String VORONOI_ANALYSIS = "VORONOI_ANALYSIS";
	
	String MAKE_POLYGON = "BUFFER_MAKE_POLYGON";
	
	String LEGEND_APPLY = "LEGEND_APPLY";
	
	String RESULT_PROCESSING = "RESULT_PROCESSING";
	
	String LEGEND_LIST = "LEGEND_LIST";
	
	String DATA_IMPORT = "DATA_IMPORT";
	
	String RESULT_SAVE = "RESULT_SAVE";
	
	String DATA_CONDITION = "DATA_CONDITION";
	String DATA_CONDITION_2016 = "DATA_CONDITION_2016";
	
	String STAT_ANALYSIS = "STAT_ANALYSIS";
	
	String STAT_DATA_CONDITION = "STAT_DATA_CONDITION";
	
	String STAT_MAKE_DATA = "STAT_MAKE_DATA";
	
	String TEMP_SCHEMA = "temp";
	
	String DATA_USED = "DATA_USED";

	String PARSING_RESULT_MODIFY = "PARSING_RESULT_MODIFY";

	String MAPPING_RE_START = "MAPPING_RE_START";

	String GEOCODE_RENEWAL = "GEOCODE_RENEWAL";

	String SCHEMAS = "SCHEMAS";

	String HIVE_DATA_LOAD = "HIVE_DATA_LOAD";

	String R_EXECUTE_QUERY = "R_EXECUTE_QUERY";
	
	String STAT_RESULT_SAVE = "STAT_RESULT_SAVE";

	String SCRIPT_CRUD = "SCRIPT_CRUD";

	String HDFS_FILE_LIST = "HDFS_FILE_LIST";
	
	String SVG_UPLOAD = "SVG_UPLOAD";

	String UNCLASSIFIED_TABLE = "UNCLASSIFIED_TABLE";

	String REGISTER = "REGISTER";

	String FILECONTENT = "FILECONTENT";
	
	String STAT_REPORT = "STAT_REPORT";
	
	String EXISTS = "EXISTS";

	String GEOCODING = "GEOCODING";
	
	String OPEN_DATA_USE_LIST = "OPEN_DATA_USE_LIST";
	
	String OPEN_DATA_USE_SUM = "OPEN_DATA_USE_SUM";

	String KAIROS = "KAIROS";

	String PUT_DATA = "PUT_DATA";
	
	String GET_DATA = "GET_DATA"; 
	
	String RESTART = "RESTART";
	
	String PROCESS_STATUS = "PROCESS_STATUS";
	
	String SYSTEM = "SYSTEM";
	
	String WEEK_EXPECT_WORKFLOW = "WEEK_EXPECT_WORKFLOW";
	
	String SEND_HIVE = "SEND_HIVE";
	
	String SEND_PG = "SEND_PG";
	
	String SAVE_EXECUTE_SELECT = "SAVE_EXECUTE_SELECT";

	String CLIENT_STATUS = "CLIENT_STATUS";
	
	String BOUNDARYKRNM = "경계";
	
	String BOUNDARYKRNM2 = "행정구역별경계";
	
	String READ = "READ";

	String VERIFY_RE_START = "VERIFY_RE_START";
	
	String EXECUTE_LIST = "EXECUTE_LIST";
	
	String COPY_TO_USER = "COPY_TO_USER";
	
	String SELECT_USER_PURPOSE = "SELECT_USER_PURPOSE";
	
	String OPEN_DATA_USER_LIST = "OPEN_DATA_USER_LIST";
	
	String UPDATE_DOWNLOAD_APPLY = "UPDATE_DOWNLOAD_APPLY";

	String REGISTER_CHECK = "REGISTER_CHECK";
	
	String BUFFER_RESTRICTION = "BUFFER_RESTRICTION";

	String DETAIL_RESTRICTION_CODE = "DETAIL_RESTRICTION_CODE";

	String RESTRICTION = "RESTRICTION";

	String UPDATE_RESTRICTION_CODE = "UPDATE_RESTRICTION_CODE";

	String SELECT_RESTRICTION_TABLE =  "SELECT_RESTRICTION_TABLE";

	String INSERT_RESTRICTION_TABLE =  "INSERT_RESTRICTION_TABLE";
	
	String DELETE_RESTRICTION_TABLE =  "DELETE_RESTRICTION_TABLE";
	
	String UPDATE_RESTRICTION_TABLE =  "UPDATE_RESTRICTION_TABLE";

	String PG_SETUSER = "PG_SETUSER";
	
	String USER_DATA_MAPPING = "USER_DATA_MAPPING";
	
	String TRANSFORM = "TRANSFORM";
	
	String USER_DATA_COORDINATE_TRANSFORM = "USER_DATA_COORDINATE_TRANSFORM";
	
	String USER_DATA_BND_MAPPING = "USER_DATA_BND_MAPPING";
	
	String BATCH_DETAIL = "BATCH_DETAIL";
	
	String SELECT_BATCH_LIST = "SELECT_BATCH_LIST";
	
	String BATCH = "BATCH";
	
	String BATCH_START = "BATCH_START";
	
	String DATA_JOB_FLOW = "DATA_JOB_FLOW";
	
	String DATA_UPLOAD_FILE_RESULT = "DATA_UPLOAD_FILE_RESULT";
	
	String UPDATE_FILE_RESULT = "UPDATE_FILE_RESULT";

	String MULTI_DELETE = "MULTI_DELETE";
	
	String SPACE_ANALYSIS = "SPACE_ANALYSIS";
	String KAIROS_PG_ANALYSIS = "KAIROS_PG_ANALYSIS";
	
	String COUNT_K = "COUNT_K";
	
	String SELECT_MAPPING_RUNNING = "SELECT_MAPPING_RUNNING";

	String USER_SHP_COORD_CONV = "USER_SHP_COORD_CONV";

	String GEOMETRY_YN = "GEOMETRY_YN";

	String GEOMETRY_YN2 = "GEOMETRY_YN2";

	String GEOMERTY_TYPE = "GEOMERTY_TYPE";
	
	String UCOA_DATA = "UCOA_DATA";
	
	String TABLE_CHECK = "TABLE_CHECK";

	String DATA_CONDITION_CENSUS = "DATA_CONDITION_CENSUS";

	// String GEO_ANALYSIS = "GEO_ANALYSIS";

	String DATA_UNION_ANALYSIS = "DATA_UNION_ANALYSIS";

	String DATA_UNION_EXECUTE_YN = "DATA_UNION_EXECUTE_YN";

	String SELECT_UNION_DATA = "SELECT_UNION_DATA";
	
	String SELECT_ANALYSIS_RESULT_INFO = "SELECT_ANALYSIS_RESULT_INFO";
	
	String SELECT_COLLECT_DETAIL = "SELECT_COLLECT_DETAIL";

	String COLLECT_LOG_SELECT = "COLLECT_LOG_SELECT";

	String MOLIT = "MOLIT";

	String DELETE_USER_DATA = "DELETE_USER_DATA";

	String MAPPING_RESULT_PREVIEW = "MAPPING_RESULT_PREVIEW";

	String USER_DATA_MAPPING_RESTART = "USER_DATA_MAPPING_RESTART";

}
